// File generated by FlutterFire CLI.
// Modified to use environment variables for API keys.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: AppConfig.firebaseAndroidApiKey,
        appId: '1:92090502132:android:e6e9ca620f27c05b3547a1',
        messagingSenderId: '92090502132',
        projectId: 'pumeun-gido-1723d',
        storageBucket: 'pumeun-gido-1723d.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: AppConfig.firebaseIosApiKey,
        appId: '1:92090502132:ios:df5a2a1c47b757be3547a1',
        messagingSenderId: '92090502132',
        projectId: 'pumeun-gido-1723d',
        storageBucket: 'pumeun-gido-1723d.firebasestorage.app',
        iosBundleId: 'com.jc.pumeun-gido',
      );
}
